name: First Workflow
on: workflow_dispatch
jobs:
    # First_Job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: This is Step 1
    #           run: echo Creating a yml file manually
    #         - name: This is Step 2
    #           run: |
    #               echo Line 1
    #               echo Line 2
    # second_Job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: This is Step 1
    #           run: echo Creating a yml file manually
    #         - name: This is Step 2
    #           run: |
    #               echo Line 1
    #               echo Line 2

    events-jobs:
      runs-on: ubuntu-latest
 
      steps:
        - name: Print greeting
          run: echo "Hello World!"
        - name: Output event data
          run: echo "${{ toJSON(github.event) }}"
        - name: Get Code
          uses: actions/checkout@v4
        - name: Install Dependencies
          run: npm install
        - name: Install Dependencies
          run: npm ci
        - name: Test
          run: npm run test
         